### Sign In (user)

POST {{baseUrl}}/auth/token
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

### Sign In (admin)

POST {{baseUrl}}/auth/token
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
