### Get Posts

GET {{baseUrl}}/posts
Authorization: Bearer {{token}}

### Get Approved Posts

GET {{baseUrl}}/posts/approved
Authorization: Bearer {{token}}

### Create Post

POST {{baseUrl}}/posts/post
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Test title",
  "content": "Test content",
  "url": "https://www.google.com/"
}

### Update Post

PUT {{baseUrl}}/posts/post
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "title": "Updated title",
  "content": "Updated content",
  "url": "https://www.google.com/"
}

### Delete Post

DELETE {{baseUrl}}/posts/post/1
Authorization: Bearer {{token}}

### Get Posts (Admin)

GET {{baseUrl}}/posts/admin
Authorization: Bearer {{token}}

### Update Post Status (Admin)

PUT {{baseUrl}}/posts/admin/post/1/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "approved"
}
