### Get Posts

GET {{baseUrl}}/posts
Authorization: Bearer {{token}}

### Get Post

GET {{baseUrl}}/posts/1
Authorization: Bearer {{token}}

### Get Approved Posts

GET {{baseUrl}}/posts/approved
Authorization: Bearer {{token}}

### Create Post

POST {{baseUrl}}/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Test title",
  "content": "Test content",
  "url": "https://www.google.com/"
}

### Update Post

PUT {{baseUrl}}/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "title": "Updated title",
  "content": "Updated content",
  "url": "https://www.google.com/"
}

### Read Review

PUT {{baseUrl}}/posts/1/read
Authorization: Bearer {{token}}

### Delete Post

DELETE {{baseUrl}}/posts/1
Authorization: Bearer {{token}}

### Get Posts (Admin)

GET {{baseUrl}}/posts/admin
Authorization: Bearer {{token}}

### Update Post Status (Admin)

PUT {{baseUrl}}/posts/admin/1/review
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "approved",
  "comment": "Post approved"
}

### Like Post

POST {{baseUrl}}/posts/1/like
Authorization: Bearer {{token}}

### Comment on Post

POST {{baseUrl}}/posts/1/comment
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "This is a comment"
}

### Cancel Like

DELETE {{baseUrl}}/posts/1/like
Authorization: Bearer {{token}}

### Revise Comment

PUT {{baseUrl}}/posts/1/comment/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "This is a revised comment"
}

### Delete Comment

DELETE {{baseUrl}}/posts/1/comment/1
Authorization: Bearer {{token}}